name: Publish Extension

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update Manifest Version
        run: |
          NEW_VERSION=${GITHUB_REF#refs/tags/v}
          jq ".version = \"$NEW_VERSION\"" manifest.json > temp.json && mv temp.json manifest.json
          echo "Manifest updated to version $NEW_VERSION"

      - name: Zip Extension
        # Wir schließen git-Daten und den GitHub-Ordner aus
        run: zip -r release.zip . -x "*.git*" ".github*" "README.md"

      - name: Upload & Publish to Chrome Web Store
        uses: mobilefirstllc/chrome-webstore-upload@v2
        with:
          file-name: 'release.zip'
          extension-id: ${{ secrets.EXTENSION_ID }}
          client-id: ${{ secrets.CLIENT_ID }}
          client-secret: ${{ secrets.CLIENT_SECRET }}
          refresh-token: ${{ secrets.REFRESH_TOKEN }}
          publish: true
